### ISSUE TITLE
This feedstock is stale and causing issues for upstream

### ISSUE THREAD

**Issue by alexreinking** [conda-forge/halide-feedstock#7]
This feedstock provides a now-ancient version of Halide that causes us headaches when users try it and run into issues. See halide/Halide#5609

If it is possible to remove it, that might be best for upstream Halide at this time. _Otherwise_, I would like to take over maintainership of this package in order to update it, assuming @jrk, @steven-johnson, and @minrk (the current listed maintainers) do not object.

**Comment by steven-johnson** [comment]
SGTM

**Comment by isuruf** [comment]
We have halide 18 packaged now and I have added myself as a maintainer. If you are still interested, we can add you as a maintainer too.

**Comment by alexreinking** [comment]
Thanks very much, @isuruf!

I would be glad to be added as a maintainer.

**Comment by isuruf** [comment]
Thanks @alexreinking for volunteering. You should have gotten an invitation. See https://github.com/conda-forge/halide-feedstock/commit/261ffe56e6f46c3fb61797e2fc1d4d812ebe9dbc#commitcomment-145464943
